name: README Build
on:
  workflow_dispatch:
  schedule:
    - cron: "*/25 * * * *"

jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
        - name: Generate README file
          uses: nclsbayona/nclsbayona-readme-action@master
          env:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
            LOCATION: ${{ secrets.LOCATION }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
